### ISSUE TITLE
Skill fails to install

### ISSUE THREAD

**Issue by pseams** [TREE-Edu/desktop-control-skill#7]
installing from home.mycroft.ai and saying "download custom skill" gives the following logs in the debug console.

08:22:34.807 - __main__:handle_utterance:61 - INFO - Utterance: ['download custom scale']
08:22:35.746 - SkillInstallerSkill - ERROR - Msm failed: AlreadyInstalled(today-history.btotharye)
08:24:44.571 - msm.skill_entry - INFO - Downloading skill: https://github.com/TREE-Edu/desktop-control-skill
08:24:45.163 - msm.skill_entry - INFO - Installing requirements.txt for desktop-control-skill
08:24:47.092 - SkillInstallerSkill - ERROR - Msm failed: PipRequirementsException(
Pip returned code 1:
Collecting python3-xlib>=0.15 (from -r /opt/mycroft/skills/desktop-control-skill.tree-edu/requirements.txt (line 1)) 
`Downloading https://files.pythonhosted.org/packages/ef/c6/2c5999de3bb1533521f1101e8fe56fd9c266732f4d48011c7c69b29d12ae/python3-xlib-0.15.tar.gz `(132kB)
`Collecting pyautogui>=0.9.36 (from -r /opt/mycroft/skills/desktop-control-skill.tree-edu/requirements.txt `(line 2)) 
`Downloading https://files.pythonhosted.org/packages/2e/83/89b5adbc37d1bbf7b486a2c1c00e8037e6f801e8c053c4897bb82d9510c6/PyAutoGUI-0.9.36.tar.gz `(46kB)
`Complete output from command python setup.py egg_info:
`Traceback (most recent call last):
`File "<string>", line 1, in <module>
`File "/tmp/pip-install-kb3pvh71/pyautogui/setup.py", line 6, in <module>
`version=__import__('pyautogui').__version__,
`File "/tmp/pip-install-kb3pvh71/pyautogui/pyautogui/__init__.py", line 115, in <module>
`from . import _pyautogui_x11 as platformModule
`File "/tmp/pip-install-kb3pvh71/pyautogui/pyautogui/_pyautogui_x11.py", line 7, in <module>
`from Xlib.display import Display
`ModuleNotFoundError: No module named 'Xlib'

`--------------`

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kb3pvh71/pyautogui/
`)
`08:24:47.256 - mycroft.skills.core:load_skill:105 - INFO - ATTEMPTING TO LOAD SKILL: desktop-`control-skill.tree-edu with ID desktop-control-skill.tree-edu
`08:24:47.259 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: desktop-control-`skill.tree-edu
`Traceback (most recent call last):
`File "/home/parker/mycroft-core/mycroft/skills/core.py", line 115, in load_skill
`('.py', 'rb', imp.PY_SOURCE)
`File "/usr/lib/python3.6/imp.py", line 235, in load_module
`return load_source(name, filename, file)
`File "/usr/lib/python3.6/imp.py", line 172, in load_source
`module = _load(spec)
`File "<frozen importlib._bootstrap>", line 684, in _load
`File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
`File "<frozen importlib._bootstrap_external>", line 678, in exec_module
`File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
`File "/opt/mycroft/skills/desktop-control-skill.tree-edu/__init__.py", line 23, in <module>
`import pyautogui
`ModuleNotFoundError: No module named 'pyautogui' `

**Comment by TREE-Edu** [comment]
Thanks for posting this issue.  We haven't tested installing through the web UI yet.  After cleaning out all requirements from our virtual env. we did a fresh test install through msm and everything installed correctly.  Could you try installing using msm and post back whether that works for you?  Thank you again.
